apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-backend
  template:
    metadata:
      labels:
        app: lms-backend
    spec:
      containers:
      - name: lms-backend
        image: yourdockerhubusername/lms-backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: lms-backend
  ports:
  - port: 8080
    targetPort: 8080
